ExamenDBustillo/ExamenDBustillo/Controllers/ComplejoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExamenDBustillo.Controllers
{
    public class ComplejoController : Controller
    {

        private db599556223afa4e37913da49d0024f159Entities _db = new db599556223afa4e37913da49d0024f159Entities();
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAll()
        {
            _db.Configuration.ProxyCreationEnabled = false;
            var lista = _db.Complejo.ToList();

            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Create(Complejo complejo)
        {
            _db.Complejo.Add(complejo);
            _db.SaveChanges();
            return Json(complejo, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Update(Complejo complejo)
        {
            _db.Entry(complejo).State = EntityState.Modified;
            _db.SaveChanges();
            return Json(complejo, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Delete(string id)
        {
            var nId = int.Parse(id);
            var complejo = _db.Complejo.FirstOrDefault(x => x.ID == nId);
            _db.Complejo.Remove(complejo);
            _db.SaveChanges();

            return Json(complejo, JsonRequestBehavior.AllowGet);
        }



    }
}

ExamenDBustillo/ExamenDBustillo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Created by David Bustillo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src=" ~/Scripts/angular.min.js"></script>
    <script src=" ~/app/app.js"></script>


</head>


<body>
   
    <style clase="text/css"> 
        .Header1, .Header2
        {
            font-family: 'Baskerville Old Face';
            font-size: 18px;
            color: #ffffff;
        }

        .a
        {
            font-family: 'Baskerville Old Face';
            font-size: 18px;
            text-align: right;
        }
    </style>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

                <ion-item nav-clear menu-close href="" side="left">
                    <img src="Images_/hn2.png" width="80" height="50" />
                </ion-item>
             

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="Header1">@Html.ActionLink("Complejo Deportivo", "Index", "Complejo")</li>
                    <li class="Header2">@Html.ActionLink("Canchas", "Index", "Canchas")</li>
                
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer >
            <p class="a">&copy; Created by David Bustillo ~ @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>